const Option = {
  float: ["left", "right", "none"],
  display: ["inline", "block", "inline-block", "flex", "none"],
  position: ["static", "relative", "absolute", "fixed"],
  top: ["px", "%", "vh", "em", "rem", "vw"],
  fontFamily: [
    "Arial",
    "Arial Black",
    "Brush Script MT",
    "Comic Sans MS",
    "Courier New",
    "Georgia",
    "Helvetica",
    "Impact",
    "Lucida Sans Unicode",
    "Tahoma",
    "Times New Roman",
    "Trebuchet MS",
    "Verdana",
  ],
  textAlign: ["left", "right", "center", "justify"],
  fontWeight: [
    "Thin",
    "Extra Light",
    "Light",
    "Normal",
    "Medium",
    "Semi Bold",
    "Bold",
    "Extra Bold",
    "Ultra Bold",
  ],
  border: [
    "none",
    "solid",
    "dotted",
    "dashed",
    "double",
    "groove",
    "ridge",
    "inset",
    "outset",
  ],
};

export default Option;
