const sameunits = [
  //   { units: "auto", name: "auto" },
  //   { units: "initial", name: "initial" },
  //   { units: "inherit", name: "inherit" },

  { units: "", name: "--" },
  { units: "px", name: "px" },
  { units: "%", name: "%" },
  { units: "vh", name: "vh" },
  { units: "em", name: "em" },
  { units: "rem", name: "rem" },
];
export let data = [
  {
    id: "FlexContainer",
    values: [
      { units: "block", name: "Disable" },
      { units: "flex", name: "Enable" },
    ],
  },
  { id: "Top", values: sameunits },
  { id: "Bottom", values: sameunits },
  { id: "Left", values: sameunits },
  { id: "Right", values: sameunits },
  { id: "Width", values: sameunits },
  { id: "Height", values: sameunits },
  { id: "MaxWidth", values: sameunits },
  { id: "MinHeight", values: sameunits },
  { id: "MarginTop", values: sameunits },
  { id: "MarginBottom", values: sameunits },
  { id: "MarginRight", values: sameunits },
  { id: "MarginLeft", values: sameunits },
  { id: "PaddingRight", values: sameunits },
  { id: "PaddingLeft", values: sameunits },
  { id: "PaddingTop", values: sameunits },
  { id: "PaddingBottom", values: sameunits },
  { id: "BorderWidth", values: sameunits },
  { id: "BorderRadiusTopLeft", values: sameunits },
  { id: "BorderRadiusTopRight", values: sameunits },
  { id: "BorderRadiusBottomLeft", values: sameunits },
  { id: "BorderRadiusBottomRight", values: sameunits },
  { id: "FontSize", values: sameunits },
  { id: "LetterSpacing", values: sameunits },
  { id: "LineHeight", values: sameunits },
  {
    id: "FontWeight",
    values: [
      { units: 100, name: "Thin" },
      { units: 200, name: "Extra Light" },
      { units: 300, name: "Light" },
      { units: 400, name: "Normal" },
      { units: 500, name: "Medium" },
      { units: 600, name: "Semi Bold" },
      { units: 700, name: "Bold" },
      { units: 800, name: "Extra Bold" },
      { units: 900, name: "Ultra Bold" },
    ],
  },
  { id: "FlexBasis", values: sameunits },
  {
    id: "Float",
    values: [
      { units: "left", name: "left" },
      { units: "right", name: "right" },
      { units: "none", name: "none" },
      { units: "inherit", name: "inherit" },
      { units: "em", name: "em" },
      { units: "vw", name: "vw" },
    ],
  },
  {
    id: "Position",
    values: [
      { units: "static", name: "static" },
      { units: "relative", name: "relative" },
      { units: "fixed", name: "fixed" },
      { units: "absolute", name: "absolute" },
    ],
  },
  {
    id: "FlexDirection",
    values: [
      { units: "row", name: "row" },
      { units: "row-reverse", name: "row-reverse" },
      { units: "column", name: "column" },
      { units: "column-reverse", name: "column-reverse" },
    ],
  },
  {
    id: "JustifyContent",
    values: [
      { units: "flex-start", name: "flex-start" },
      { units: "flex-end", name: "flex-end" },
      { units: "space-between", name: "space-between" },
      { units: "space-around", name: "space-around" },
    ],
  },
  {
    id: "AlignItems",
    values: [
      { units: "flex-start", name: "flex-start" },
      { units: "flex-end", name: "flex-end" },
      { units: "stretch", name: "stretch" },
      { units: "center", name: "center" },
    ],
  },
  {
    id: "AlignSelf",
    values: [
      { units: "flex-start", name: "flex-start" },
      { units: "flex-end", name: "flex-end" },
      { units: "stretch", name: "stretch" },
      { units: "center", name: "center" },
    ],
  },
  {
    id: "TextAlign",
    values: [
      { units: "left", name: "Left" },
      { units: "right", name: "Right" },
      { units: "center", name: "Center" },
      { units: "justify", name: "Justify" },
    ],
  },
  {
    id: "Display",
    values: [
      { units: "inline", name: "inline" },
      { units: "block", name: "block" },
      { units: "inline-block", name: "inline-block" },
      { units: "flex", name: "flex" },
      { units: "none", name: "none" },
      { units: "hidden", name: "hidden" },
    ],
  },
  {
    id: "BorderStyle",
    values: [
      { units: "none", name: "none" },
      { units: "solid", name: "solid" },
      { units: "dotted", name: "dotted" },
      { units: "dashed", name: "dashed" },
      { units: "double", name: "double" },
      { units: "groove", name: "groove" },
      { units: "ridge", name: "ridge" },
      { units: "inset", name: "inset" },
      { units: "outset", name: "outset" },
    ],
  },
  {
    id: "FontFamily",
    values: [
      { units: "Arial", name: "Arial" },
      { units: "Arial Black", name: "Arial Black" },
      { units: "Brush Script MT", name: "Brush Script MT" },
      { units: "Comic Sans MS", name: "Comic Sans MS" },
      { units: "Courier New", name: "Courier New" },
      { units: "Georgia", name: "Georgia" },
      { units: "Helvetica", name: "Helvetica" },
      { units: "Impact", name: "Impact" },
      {
        units: "Lucida Sans Unicode",
        name: "Lucida Sans Unicode",
      },
      { units: "Tahoma", name: "Tahoma" },
      { units: "Times New Roman", name: "Times New Roman" },
      { units: "Trebuchet MS", name: "Trebuchet MS" },
      { units: "Verdana", name: "Verdana" },
    ],
  },
];
