export let data =[
    {id:"FlexContainer",values:[{units:"block",name:"Disable"},{units:"flex",name:"Enable"}]},
    {id:"Top",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"Bottom",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"Left",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"Right",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"Width",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"Height",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"MaxWidth",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"MinHeight",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"MarginTop",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"MarginBottom",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"MarginRight",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"MarginLeft",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"PaddingRight",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"PaddingLeft",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"PaddingTop",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"PaddingBottom",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"BorderWidth",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"BorderRadiusTopLeft",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"BorderRadiusTopRight",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"BorderRadiusBottomLeft",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"BorderRadiusBottomRight",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"FontSize",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"LetterSpacing",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"LineHeight",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"FontWeight",values:[{units:100,name:"Thin"},{units:200,name:"Extra Light"},{units:300,name:"Light"},{units:400,name:"Normal"},{units:500,name:"Medium"},{units:600,name:"Semi Bold"},{units:700,name:"Bold"},{units:800,name:"Extra Bold"},{units:900,name:"Ultra Bold"}]},
    {id:"FlexBasis",values:[{units:"px",name:"px"},{units:"%",name:"%"},{units:"vh",name:"vh"},{units:"em",name:"em"},{units:"rem",name:"rem"}]},
    {id:"Float",values:[{units:"left",name:"left"},{units:"right",name:"right"},{units:"none",name:"none"},{units:"inherit",name:"inherit"},{units:"em",name:"em"},{units:"vw",name:"vw"}]},
    {id:"Position",values:[{units:"static",name:"static"},{units:"relative",name:"relative"},{units:"fixed",name:"fixed"},{units:"absolute",name:"absolute"}]},
    {id:"FlexDirection",values:[{units:"row",name:"row"},{units:"row-reverse",name:"row-reverse"},{units:"column",name:"column"},{units:"column-reverse",name:"column-reverse"}]},
    {id:"JustifyContent",values:[{units:"flex-start",name:"flex-start"},{units:"flex-end",name:"flex-end"},{units:"space-between",name:"space-between"},{units:"space-around",name:"space-around"}]},
    {id:"AlignItems",values:[{units:"flex-start",name:"flex-start"},{units:"flex-end",name:"flex-end"},{units:"stretch",name:"stretch"},{units:"center",name:"center"}]},
    {id:"AlignSelf",values:[{units:"flex-start",name:"flex-start"},{units:"flex-end",name:"flex-end"},{units:"stretch",name:"stretch"},{units:"center",name:"center"}]},
    {id:"TextAlign",values:[{units:"left",name:"Left"},{units:"right",name:"Right"},{units:"center",name:"Center"},{units:"justify",name:"Justify"}]},
    {id:"Display",values:[{units:"inline",name:"inline"},{units:"block",name:"block"},{units:"inline-block",name:"inline-block"},{units:"flex",name:"flex"},{units:"none",name:"none"},{units:"hidden",name:"hidden"}]},
    {id:"BorderStyle",values:[{units:"none",name:"none"},{units:"solid",name:"solid"},{units:"dotted",name:"dotted"},{units:"dashed",name:"dashed"},{units:"double",name:"double"},{units:"groove",name:"groove"},{units:"ridge",name:"ridge"},{units:"inset",name:"inset"},{units:"outset",name:"outset"}]},
    {id:"FontFamily",values:[{units:"Arial, Helvetica, sans-serif",name:"Arial"},{units:"Arial Black, Gadget, sans-serif",name:"Arial Black"},{units:"Brush Script MT, sans-serif",name:"Brush Script MT"},{units:"Comic Sans MS, cursive, sans-serif",name:"Comic Sans MS"},{units:"Courier New, Courier, monospace",name:"Courier New"},{units:"Georgia, serif",name:"Georgia"},{units:"Helvetica, sans-serif",name:"Helvetica"},{units:"Charcoal, sans-serif",name:"Impact"},{units:"Lucida Sans Unicode, Lucida Grande, sans-serif",name:"Lucida Sans Unicode"},{units:"Tahoma, Geneva, sans-serif",name:"Tahoma"},{units:"Times New Roman, Times, serif",name:"Times New Roman"},{units:"Trebuchet MS, Helvetica, sans-serif",name:"Trebuchet MS"},{units:"Verdana, Geneva, sans-serif",name:"Verdana"}]},
]

